version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/BuildTools"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
  - package-ecosystem: "github-actions"
    directories: ["/", "/.github/actions/*"]
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    groups:
      github-actions:
        patterns: ["*"]
