disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - line_length
  - type_body_length
  - type_name
opt_in_rules:
  - closure_spacing
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
included:
  - DiceKeys
  - Tests
  - seed-security-key
  - Packages/DiceKeysCore/Sources/SeededCrypto
  - Packages/DiceKeysCore/Sources/ReadDiceKey
  - Packages/DiceKeysCore/Tests
excluded:
  - Packages/DiceKeysCore/Sources/CSodium
  - Packages/DiceKeysCore/Sources/SeededCryptoNative
