// swift-tools-version: 6.3
//
// ReadDiceKey: the DiceKey scanner, in Swift, and the face specification it reads with. The
// app uses both. See docs/SCANNING.md.
//
//   DiceKeySpecification  the faces and their printed layout, generated by DiceKeys
//   ReadDiceKey           the scanner

import PackageDescription

let package = Package(
    name: "ReadDiceKey",
    platforms: [
        .iOS(.v26),
        .macOS(.v26)
    ],
    products: [
        .library(name: "DiceKeySpecification", targets: ["DiceKeySpecification"]),
        .library(name: "ReadDiceKey", targets: ["ReadDiceKey"])
    ],
    targets: [
        .target(name: "DiceKeySpecification"),
        // Always optimized, because unoptimized it is too slow for a Debug build to read a
        // key. Unsafe flags are allowed here because the package is a local path dependency.
        .target(
            name: "ReadDiceKey",
            dependencies: ["DiceKeySpecification"],
            swiftSettings: [
                .unsafeFlags(["-O"], .when(configuration: .debug))
            ]
        ),
        .testTarget(
            name: "ReadDiceKeyTests",
            dependencies: ["ReadDiceKey", "DiceKeySpecification"],
            resources: [.copy("Fixtures")]
        )
    ]
)
