//
//  Generated by scripts/generate-wordlists.py; do not edit by hand.
//  Source: https://www.unicode.org/Public/18.0.0/emoji/emoji-test.txt.
//  Rule: curate_emoji(), Unicode emoji 18.0, up to E14.0.
//  The Unicode data file is used under the Unicode License v3 (see THIRD_PARTY_LICENSES).
//  The order is part of every password derived with this list and cannot change.
//

let emojiWords: [String] = [
    "💀",  // skull
    "💩",  // pile of poo
    "👽",  // alien
    "👾",  // alien monster
    "🤖",  // robot
    "💥",  // collision
    "🧠",  // brain
    "🫀",  // anatomical heart
    "🦷",  // tooth
    "🦴",  // bone
    "👀",  // eyes
    "🐵",  // monkey face
    "🦍",  // gorilla
    "🐶",  // dog face
    "🐕",  // dog
    "🐩",  // poodle
    "🐺",  // wolf
    "🦊",  // fox
    "🦝",  // raccoon
    "🐱",  // cat face
    "🐈",  // cat
    "🦁",  // lion
    "🐯",  // tiger face
    "🐆",  // leopard
    "🐴",  // horse face
    "🦄",  // unicorn
    "🦓",  // zebra
    "🦌",  // deer
    "🦬",  // bison
    "🐮",  // cow face
    "🐄",  // cow
    "🐷",  // pig face
    "🐖",  // pig
    "🐗",  // boar
    "🐑",  // ewe
    "🐐",  // goat
    "🐪",  // camel
    "🦙",  // llama
    "🦒",  // giraffe
    "🐘",  // elephant
    "🦏",  // rhinoceros
    "🐁",  // mouse
    "🐹",  // hamster
    "🐰",  // rabbit face
    "🐇",  // rabbit
    "🦔",  // hedgehog
    "🦇",  // bat
    "🐻",  // bear
    "🐨",  // koala
    "🐼",  // panda
    "🦥",  // sloth
    "🦦",  // otter
    "🦨",  // skunk
    "🦘",  // kangaroo
    "🐾",  // paw prints
    "🦃",  // turkey
    "🐔",  // chicken
    "🐓",  // rooster
    "🐤",  // baby chick
    "🐦",  // bird
    "🐧",  // penguin
    "🦅",  // eagle
    "🦆",  // duck
    "🦢",  // swan
    "🦉",  // owl
    "🦤",  // dodo
    "🪶",  // feather
    "🦩",  // flamingo
    "🦚",  // peacock
    "🦜",  // parrot
    "🐸",  // frog
    "🐊",  // crocodile
    "🐢",  // turtle
    "🦎",  // lizard
    "🐍",  // snake
    "🐉",  // dragon
    "🦕",  // sauropod
    "🦖",  // T-Rex
    "🐳",  // spouting whale
    "🐬",  // dolphin
    "🦭",  // seal
    "🐠",  // tropical fish
    "🐡",  // blowfish
    "🦈",  // shark
    "🐙",  // octopus
    "🐚",  // spiral shell
    "🪸",  // coral
    "🦀",  // crab
    "🦞",  // lobster
    "🦑",  // squid
    "🐌",  // snail
    "🦋",  // butterfly
    "🐛",  // bug
    "🐜",  // ant
    "🐝",  // honeybee
    "🪲",  // beetle
    "🐞",  // lady beetle
    "🦗",  // cricket
    "🦂",  // scorpion
    "🦟",  // mosquito
    "🪱",  // worm
    "🦠",  // microbe
    "💐",  // bouquet
    "🌸",  // cherry blossom
    "🌹",  // rose
    "🌺",  // hibiscus
    "🌻",  // sunflower
    "🌷",  // tulip
    "🌱",  // seedling
    "🪴",  // potted plant
    "🌲",  // evergreen tree
    "🌳",  // deciduous tree
    "🌴",  // palm tree
    "🌵",  // cactus
    "🌾",  // sheaf of rice
    "🌿",  // herb
    "🍀",  // four leaf clover
    "🍁",  // maple leaf
    "🪺",  // nest with eggs
    "🍄",  // mushroom
    "🍇",  // grapes
    "🍈",  // melon
    "🍉",  // watermelon
    "🍊",  // tangerine
    "🍋",  // lemon
    "🍌",  // banana
    "🍍",  // pineapple
    "🥭",  // mango
    "🍎",  // red apple
    "🍐",  // pear
    "🍑",  // peach
    "🍒",  // cherries
    "🍓",  // strawberry
    "🫐",  // blueberries
    "🥝",  // kiwi fruit
    "🫒",  // olive
    "🥥",  // coconut
    "🥑",  // avocado
    "🍆",  // eggplant
    "🥔",  // potato
    "🥕",  // carrot
    "🌽",  // ear of corn
    "🫑",  // bell pepper
    "🥒",  // cucumber
    "🥬",  // leafy green
    "🥦",  // broccoli
    "🧄",  // garlic
    "🥜",  // peanuts
    "🫘",  // beans
    "🌰",  // chestnut
    "🍞",  // bread
    "🥐",  // croissant
    "🥖",  // baguette bread
    "🥨",  // pretzel
    "🥞",  // pancakes
    "🧇",  // waffle
    "🧀",  // cheese wedge
    "🍗",  // poultry leg
    "🥩",  // cut of meat
    "🥓",  // bacon
    "🍔",  // hamburger
    "🍟",  // french fries
    "🍕",  // pizza
    "🌭",  // hot dog
    "🥪",  // sandwich
    "🌮",  // taco
    "🌯",  // burrito
    "🥚",  // egg
    "🍳",  // cooking
    "🫕",  // fondue
    "🥗",  // green salad
    "🍿",  // popcorn
    "🧂",  // salt
    "🥫",  // canned food
    "🍱",  // bento box
    "🍙",  // rice ball
    "🍚",  // cooked rice
    "🍛",  // curry rice
    "🍜",  // steaming bowl
    "🍝",  // spaghetti
    "🍠",  // roasted sweet potato
    "🍣",  // sushi
    "🍤",  // fried shrimp
    "🍥",  // fish cake with swirl
    "🍡",  // dango
    "🥟",  // dumpling
    "🥡",  // takeout box
    "🍦",  // soft ice cream
    "🍧",  // shaved ice
    "🍩",  // doughnut
    "🍪",  // cookie
    "🎂",  // birthday cake
    "🍰",  // shortcake
    "🧁",  // cupcake
    "🥧",  // pie
    "🍫",  // chocolate bar
    "🍬",  // candy
    "🍭",  // lollipop
    "🍮",  // custard
    "🍯",  // honey pot
    "🍼",  // baby bottle
    "🥛",  // glass of milk
    "☕",  // hot beverage
    "🫖",  // teapot
    "🍶",  // sake
    "🍾",  // bottle with popping cork
    "🍷",  // wine glass
    "🍸",  // cocktail glass
    "🍹",  // tropical drink
    "🍺",  // beer mug
    "🥂",  // clinking glasses
    "🥃",  // tumbler glass
    "🧋",  // bubble tea
    "🧃",  // beverage box
    "🧉",  // mate
    "🧊",  // ice
    "🥢",  // chopsticks
    "🥄",  // spoon
    "🔪",  // kitchen knife
    "🫙",  // jar
    "🏺",  // amphora
    "🌍",  // globe showing Europe-Africa
    "🧭",  // compass
    "🌋",  // volcano
    "🗻",  // mount fuji
    "🧱",  // brick
    "🪨",  // rock
    "🪵",  // wood
    "🛖",  // hut
    "🏠",  // house
    "🏭",  // factory
    "🏰",  // castle
    "🗼",  // Tokyo tower
    "🗽",  // Statue of Liberty
    "⛪",  // church
    "🕋",  // kaaba
    "⛲",  // fountain
    "⛺",  // tent
    "🎠",  // carousel horse
    "🛝",  // playground slide
    "🎡",  // ferris wheel
    "🎢",  // roller coaster
    "💈",  // barber pole
    "🚂",  // locomotive
    "🚃",  // railway car
    "🚇",  // metro
    "🚌",  // bus
    "🚐",  // minibus
    "🚑",  // ambulance
    "🚒",  // fire engine
    "🚓",  // police car
    "🚕",  // taxi
    "🚗",  // automobile
    "🚙",  // sport utility vehicle
    "🚚",  // delivery truck
    "🚜",  // tractor
    "🛵",  // motor scooter
    "🦽",  // manual wheelchair
    "🛺",  // auto rickshaw
    "🚲",  // bicycle
    "🛴",  // kick scooter
    "🛹",  // skateboard
    "🛼",  // roller skate
    "🚏",  // bus stop
    "⛽",  // fuel pump
    "🛞",  // wheel
    "🚨",  // police car light
    "🚦",  // vertical traffic light
    "🛑",  // stop sign
    "🚧",  // construction
    "⚓",  // anchor
    "🛟",  // ring buoy
    "⛵",  // sailboat
    "🛶",  // canoe
    "🚤",  // speedboat
    "🚢",  // ship
    "🪂",  // parachute
    "💺",  // seat
    "🚁",  // helicopter
    "🚠",  // mountain cableway
    "🚀",  // rocket
    "🛸",  // flying saucer
    "🧳",  // luggage
    "⌛",  // hourglass done
    "⌚",  // watch
    "⏰",  // alarm clock
    "🌕",  // full moon
    "🌙",  // crescent moon
    "🌞",  // sun with face
    "🪐",  // ringed planet
    "⭐",  // star
    "⛅",  // sun behind cloud
    "🌀",  // cyclone
    "🌈",  // rainbow
    "☔",  // umbrella with rain drops
    "⚡",  // high voltage
    "⛄",  // snowman without snow
    "🔥",  // fire
    "💧",  // droplet
    "🌊",  // water wave
    "🎃",  // jack-o-lantern
    "🎄",  // Christmas tree
    "🧨",  // firecracker
    "✨",  // sparkles
    "🎈",  // balloon
    "🎉",  // party popper
    "🎊",  // confetti ball
    "🎋",  // tanabata tree
    "🎍",  // pine decoration
    "🎎",  // Japanese dolls
    "🎏",  // carp streamer
    "🧧",  // red envelope
    "🎀",  // ribbon
    "🎁",  // wrapped gift
    "🎫",  // ticket
    "🏆",  // trophy
    "🏅",  // sports medal
    "⚽",  // soccer ball
    "⚾",  // baseball
    "🏀",  // basketball
    "🏐",  // volleyball
    "🏈",  // american football
    "🎾",  // tennis
    "🎳",  // bowling
    "🏏",  // cricket game
    "🏒",  // ice hockey
    "🥍",  // lacrosse
    "🏓",  // ping pong
    "🏸",  // badminton
    "🥊",  // boxing glove
    "🥋",  // martial arts uniform
    "🥅",  // goal net
    "⛳",  // flag in hole
    "🎣",  // fishing pole
    "🤿",  // diving mask
    "🎽",  // running shirt
    "🎿",  // skis
    "🛷",  // sled
    "🥌",  // curling stone
    "🎯",  // bullseye
    "🪀",  // yo-yo
    "🪁",  // kite
    "🔫",  // water pistol
    "🎱",  // pool 8 ball
    "🔮",  // crystal ball
    "🪄",  // magic wand
    "🎮",  // video game
    "🎰",  // slot machine
    "🎲",  // game die
    "🧩",  // puzzle piece
    "🧸",  // teddy bear
    "🪅",  // piñata
    "🪩",  // mirror ball
    "🪆",  // nesting dolls
    "🀄",  // mahjong red dragon
    "🎭",  // performing arts
    "🎨",  // artist palette
    "🧵",  // thread
    "🪡",  // sewing needle
    "🧶",  // yarn
    "🪢",  // knot
    "👓",  // glasses
    "🦺",  // safety vest
    "👔",  // necktie
    "👕",  // t-shirt
    "👖",  // jeans
    "🧣",  // scarf
    "🧤",  // gloves
    "🧥",  // coat
    "🧦",  // socks
    "👗",  // dress
    "👘",  // kimono
    "👙",  // bikini
    "👛",  // purse
    "👜",  // handbag
    "🎒",  // backpack
    "🩴",  // thong sandal
    "👞",  // man’s shoe
    "👟",  // running shoe
    "🥾",  // hiking boot
    "👠",  // high-heeled shoe
    "🩰",  // ballet shoes
    "👑",  // crown
    "👒",  // woman’s hat
    "🎩",  // top hat
    "🎓",  // graduation cap
    "🧢",  // billed cap
    "🪖",  // military helmet
    "📿",  // prayer beads
    "💄",  // lipstick
    "💍",  // ring
    "💎",  // gem stone
    "🔊",  // speaker high volume
    "📣",  // megaphone
    "📯",  // postal horn
    "🔔",  // bell
    "🎼",  // musical score
    "🎵",  // musical note
    "🎶",  // musical notes
    "🎤",  // microphone
    "🎧",  // headphone
    "📻",  // radio
    "🎷",  // saxophone
    "🎺",  // trumpet
    "🪗",  // accordion
    "🎸",  // guitar
    "🎹",  // musical keyboard
    "🎻",  // violin
    "🪕",  // banjo
    "🥁",  // drum
    "🪘",  // long drum
    "📱",  // mobile phone
    "📞",  // telephone receiver
    "📟",  // pager
    "📠",  // fax machine
    "🔋",  // battery
    "🔌",  // electric plug
    "💻",  // laptop
    "💾",  // floppy disk
    "🧮",  // abacus
    "🎥",  // movie camera
    "🎬",  // clapper board
    "📺",  // television
    "📷",  // camera
    "📼",  // videocassette
    "🔍",  // magnifying glass tilted left
    "💡",  // light bulb
    "🔦",  // flashlight
    "🏮",  // red paper lantern
    "🪔",  // diya lamp
    "📔",  // notebook with decorative cover
    "📖",  // open book
    "📚",  // books
    "📜",  // scroll
    "📰",  // newspaper
    "🔖",  // bookmark
    "🪙",  // coin
    "💰",  // money bag
    "💵",  // dollar banknote
    "💳",  // credit card
    "📧",  // e-mail
    "📦",  // package
    "📫",  // closed mailbox with raised flag
    "📮",  // postbox
    "📝",  // memo
    "💼",  // briefcase
    "📁",  // file folder
    "📅",  // calendar
    "📊",  // bar chart
    "📋",  // clipboard
    "📍",  // round pushpin
    "📎",  // paperclip
    "📏",  // straight ruler
    "📐",  // triangular ruler
    "🔒",  // locked
    "🔑",  // key
    "🔨",  // hammer
    "🪓",  // axe
    "💣",  // bomb
    "🪃",  // boomerang
    "🏹",  // bow and arrow
    "🪚",  // carpentry saw
    "🔧",  // wrench
    "🪛",  // screwdriver
    "🔩",  // nut and bolt
    "🦯",  // white cane
    "🔗",  // link
    "🪝",  // hook
    "🧰",  // toolbox
    "🧲",  // magnet
    "🪜",  // ladder
    "🧪",  // test tube
    "🧫",  // petri dish
    "🧬",  // dna
    "🔬",  // microscope
    "🔭",  // telescope
    "📡",  // satellite antenna
    "💉",  // syringe
    "🩸",  // drop of blood
    "💊",  // pill
    "🩹",  // adhesive bandage
    "🩼",  // crutch
    "🩺",  // stethoscope
    "🩻",  // x-ray
    "🚪",  // door
    "🛗",  // elevator
    "🪞",  // mirror
    "🪟",  // window
    "🪑",  // chair
    "🚽",  // toilet
    "🪠",  // plunger
    "🚿",  // shower
    "🛁",  // bathtub
    "🪤",  // mouse trap
    "🪒",  // razor
    "🧴",  // lotion bottle
    "🧹",  // broom
    "🧺",  // basket
    "🧻",  // roll of paper
    "🪣",  // bucket
    "🧼",  // soap
    "🫧",  // bubbles
    "🪥",  // toothbrush
    "🧽",  // sponge
    "🧯",  // fire extinguisher
    "🛒",  // shopping cart
    "🪦",  // headstone
    "🧿",  // nazar amulet
    "🪬",  // hamsa
    "🗿",  // moai
    "🪧",  // placard
    "🪪"  // identification card
]
