//
//  ExtensionVectorTests.swift
//  DerivationTests
//
//  Fixtures/extensions.json records this app's extensions to the reference format: the
//  new lists, the modern joining and the character-set length rule. Unlike vectors.json it
//  was generated by this engine, so it can be regenerated, but only to add cases: a changed
//  value means a changed password for someone.
//
//  Regenerate: REGENERATE_EXTENSIONS_FIXTURE=1 swift test --filter ExtensionVectorTests/regenerate
//

import Foundation
import Testing

@testable import Derivation

struct ExtensionVector: Codable, Sendable, CustomTestStringConvertible {
    var testDescription: String { name }
    let name: String
    let recipe: String
    let password: String
    let json: String
}

struct ExtensionFixture: Codable, Sendable {
    let origin: String
    let seed: String
    let cases: [ExtensionVector]
}

private let fixtureURL: URL = {
    var url = URL(fileURLWithPath: #filePath)
    url.deleteLastPathComponent()
    url.append(path: "Fixtures/extensions.json")
    return url
}()

let extensionFixture: ExtensionFixture = {
    // swiftlint:disable:next force_try
    try! JSONDecoder().decode(ExtensionFixture.self, from: Data(contentsOf: fixtureURL))
}()

/// Every case the fixture holds. Add here, regenerate, and never remove or edit a line.
private let recipes: [(name: String, recipe: String)] = {
    let eff = WordList.effLarge.rawValue
    let emoji = WordList.emoji.rawValue
    var list: [(String, String)] = [
        ("EFF default length", #"{"wordList":"\#(eff)"}"#),
        ("EFF 6 words hyphens", #"{"lengthInWords":6,"separator":"-","wordList":"\#(eff)"}"#),
        ("EFF 128 bits reference", #"{"lengthInBits":128,"wordList":"\#(eff)"}"#),
        ("EFF capitalize", #"{"lengthInWords":6,"separator":"-","capitalize":true,"wordList":"\#(eff)"}"#),
        ("EFF digits capitalize", #"{"capitalize":true,"lengthInWords":6,"separator":"digits","wordList":"\#(eff)"}"#),
        ("EFF truncated modern", #"{"lengthInChars":16,"lengthInWords":6,"separator":"-","wordList":"\#(eff)"}"#),
        ("512 reference still", #"{"purpose":"x"}"#),
        ("512 modern one word", #"{"lengthInWords":1,"separator":"digits","capitalize":true}"#),
        ("1024 reference truncated", #"{"lengthInChars":20,"wordList":"EN_1024_words_6_chars_max_ed_4_20200917"}"#),
        ("emoji default", #"{"wordList":"\#(emoji)"}"#),
        ("emoji 6", #"{"lengthInChars":6,"wordList":"\#(emoji)"}"#),
        ("emoji words then truncated", #"{"lengthInChars":4,"lengthInWords":10,"wordList":"\#(emoji)"}"#),
        (
            "chars 67 words and chars",
            #"{"lengthInChars":4,"lengthInWords":10,"wordList":"\#(WordList.lettersDigitsSymbols.rawValue)"}"#
        )
    ]
    for separator in Separator.allCases {
        list.append(
            ("512 6 words separator \(separator)", #"{"lengthInWords":6,"separator":"\#(separator.rawValue)"}"#))
    }
    for set in [WordList.lettersDigitsSymbols, .lettersDigits, .lettersSymbols, .letters] {
        list.append(("\(set) 20", #"{"lengthInChars":20,"wordList":"\#(set.rawValue)"}"#))
    }
    list.append(("PIN 6", #"{"lengthInChars":6,"wordList":"\#(WordList.digits.rawValue)"}"#))
    list.append(("PIN 12", #"{"lengthInChars":12,"wordList":"\#(WordList.digits.rawValue)"}"#))
    return list
}()

@Suite("Extension vectors, generated by this engine")
struct ExtensionVectorTests {
    @Test("the fixture says where it came from and covers every recipe listed here")
    func shape() {
        #expect(extensionFixture.origin.contains("generated"))
        #expect(extensionFixture.seed == fixture.diceKeys[0].seed)
        #expect(extensionFixture.cases.map(\.recipe) == recipes.map(\.recipe))
    }

    @Test("every case derives to its recorded password and JSON", arguments: extensionFixture.cases)
    func derives(vector: ExtensionVector) throws {
        let password = try Password.derive(seed: extensionFixture.seed, recipe: vector.recipe)
        #expect(password.password == vector.password)
        #expect(password.toJson() == vector.json)
    }

    @Test(
        "regenerate the fixture",
        .enabled(if: ProcessInfo.processInfo.environment["REGENERATE_EXTENSIONS_FIXTURE"] == "1"))
    func regenerate() throws {
        let seed = fixture.diceKeys[0].seed
        let cases = try recipes.map { name, recipe in
            let password = try Password.derive(seed: seed, recipe: recipe)
            return ExtensionVector(name: name, recipe: recipe, password: password.password, json: password.toJson())
        }
        for recorded in extensionFixture.cases {
            let regenerated = try #require(cases.first { $0.recipe == recorded.recipe }, "\(recorded.name) is gone")
            try #require(
                regenerated.password == recorded.password && regenerated.json == recorded.json,
                "\(recorded.name) changed; a recorded value is someone's password")
        }
        let generated = ExtensionFixture(
            origin:
                "generated by Packages/Derivation (ExtensionVectorTests.regenerate); this app's extensions, not the reference",
            seed: seed, cases: cases)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        try encoder.encode(generated).write(to: fixtureURL)
    }
}
