#!/usr/bin/env python3
"""Writes Packages/Derivation/Sources/Derivation/WordLists.swift from the two word list
headers vendored with seeded-crypto. The lists are part of every password ever derived, so
they are copied, never edited; this script exists so the copy can be checked against its
source for as long as the source is in the tree."""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "Packages/SeededCrypto/Vendor/seeded-crypto/lib-seeded/externally-generated/word-lists"
TARGET = ROOT / "Packages/Derivation/Sources/Derivation/WordLists.swift"
LISTS = [
    ("en512Words", "EN_512_words_5_chars_max_ed_4_20200917", 512),
    ("en1024Words", "EN_1024_words_6_chars_max_ed_4_20200917", 1024),
]

out = [
    "//",
    "//  WordLists.swift",
    "//  Derivation",
    "//",
    "//  Generated by scripts/generate-word-lists.py from the seeded-crypto word lists. A word",
    "//  is chosen by index, so the order is part of every password ever derived.",
    "//",
    "",
]
for name, header, expected in LISTS:
    words = re.findall(r'"([a-z]+)"', (SOURCE / f"{header}.hpp").read_text())
    assert len(words) == expected, (name, len(words))
    assert len(set(words)) == expected, name
    out.append(f"let {name}: [String] = [")
    for i in range(0, expected, 8):
        out.append("    " + ", ".join(f'"{w}"' for w in words[i : i + 8]) + ("," if i + 8 < expected else ""))
    out.append("]")
    out.append("")
TARGET.write_text("\n".join(out))
print(f"Wrote {TARGET.relative_to(ROOT)}")
