#!/usr/bin/env python3
"""Fetches and converts the word lists this app adds to the DiceKeys recipe format.

Each list is a Swift array in Packages/Derivation/Sources/Derivation. An entry is chosen as an
8-byte block modulo the list size, so the order is part of every password ever derived with
the list: regenerate only to add a list, never to change one that has shipped.

  eff     EFF's large wordlist, verbatim (CC-BY 4.0).
  emoji   512 emoji chosen from Unicode's emoji-test.txt by the rule in curate_emoji(), minus
          EXCLUDED_EMOJI, which is the hand-curated part.

Run:  python3 scripts/generate-wordlists.py eff|emoji   (standard library only)
"""

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "Packages" / "Derivation" / "Sources" / "Derivation"

EFF_URL = "https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt"
EMOJI_TEST_URL = "https://www.unicode.org/Public/18.0.0/emoji/emoji-test.txt"
EMOJI_GROUPS = ("Animals & Nature", "Food & Drink", "Travel & Places", "Activities", "Objects")
EMOJI_COUNT = 512
# Newer emoji are left out because devices draw them only after an OS update.
EMOJI_MAX_VERSION = 14.0

# Look-alikes and obscurities removed by hand so that exactly EMOJI_COUNT remain. Edit this
# list to curate; the script fails if the count is off.
EXCLUDED_EMOJI = set(
    """
    🐒 🦧 🦮 🐅 🐎 🐂 🐃 🐽 🐏 🦣 🐀 🦫 🦡 🐥 🐲 🐋
    🦪 🪳 🪰 💮 🪷 🥀 🍂 🍃 🪹 🧅 🫓 🥯 🫔 🥙 🧆 🥣
    🧈 🍘 🍢 🥮 🥠 🍨 🍻 🫗 🥤 🌎 🌏 🌐 🗾 🏣 🏤 🏩
    🏬 💒 🌁 🌇 🚄 🚅 🚆 🚈 🚊 🚝 🚞 🚍 🚎 🚔 🚖 🚘
    🛻 🦼 🚥 🚟 🚡 ⏳ 🕛 🕧 🕜 🕑 🕝 🕞 🕓 🕟 🕔 🕠
    🕡 🕖 🕢 🕗 🕣 🕤 🕙 🕥 🕚 🕦 🌒 🌔 🌖 🌘 🎑 🥏
    🥽 🥼 🥻 🩱 🩲 🩳 👚 👝 🥿 👡 👢 🔇 🔈 🔉 📲 🪫
    🔎 📕 📗 📘 📙 📓 📒 📄 📑 💴 💶 💷 🧾 💹 📨 📩
    📤 📥 📪 📬 📭 📂 📆 📇 📉 🔏 🚬 🕐 🕒 🕕 🕘 🛫
    🛬 🌃 🌄 🌅 🌆 🌉 🌌 🎆 🎇 💿 📀 💽 🌑 🌓 🌗 🌚
    🌛 🌜 🌝 🏢 🏥 🏦 🏨 🏪 🏫 🔓 🔐 🥇 🥈 🥉 🕌 🛕
    🕍 🐫 🏡 🏯 🍏 🍅 🐟 🐣 🌼 🥘 🍴 🎪 🚉 🚋 🚛 🌟
    🌠 🌂 🥎 🏉 🏑 📢 🔕 📸 📹 💸 📈 📌 🧷 🎴 🐭 🦛
    🍖 🍲 🍵 📃 🦐 🎐 🃏
    """.split()
)
# Wanted despite being outside EMOJI_GROUPS.
INCLUDED_EMOJI = set("💀 🤖 👽 👾 💩 🧠 🫀 🦷 🦴 👀 💥".split())


def fetch(url):
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8")


def swift_header(origin, extra=""):
    return (
        "//\n"
        "//  Generated by scripts/generate-wordlists.py; do not edit by hand.\n"
        f"//  {origin}\n"
        f"{extra}"
        "//  The order is part of every password derived with this list and cannot change.\n"
        "//\n\n"
    )


def write_eff():
    lines = fetch(EFF_URL).splitlines()
    words = [line.split("\t")[1] for line in lines if "\t" in line]
    if len(words) != 7776 or len(set(words)) != 7776:
        sys.exit(f"expected 7776 unique EFF words, got {len(words)}")
    rows = [", ".join(f'"{w}"' for w in words[i : i + 8]) for i in range(0, len(words), 8)]
    body = "let effLargeWords: [String] = [\n    " + ",\n    ".join(rows) + "\n]\n"
    path = OUT / "WordLists+EFF.swift"
    path.write_text(swift_header(f"Source: {EFF_URL} (EFF large wordlist, 2016-07-19, CC-BY 4.0).") + body)
    print(f"wrote {path.relative_to(ROOT)} ({len(words)} words)")


def curate_emoji(test_text):
    """(code point, name) in emoji-test.txt order: single code point, fully qualified, in
    EMOJI_GROUPS or INCLUDED_EMOJI, emoji version at most EMOJI_MAX_VERSION, minus
    EXCLUDED_EMOJI. A fully qualified single code point always has emoji presentation, and the
    groups hold no modifiers, components or regional indicators."""
    group = None
    chosen = []
    for line in test_text.splitlines():
        if line.startswith("# group:"):
            group = line.split(":", 1)[1].strip()
            continue
        if not line or line.startswith("#"):
            continue
        code_points, rest = line.split(";", 1)
        points = code_points.split()
        status = rest.split("#")[0].strip()
        if len(points) != 1 or status != "fully-qualified":
            continue
        version, name = re.search(r"#\s*\S+\s+E(\d+\.\d+)\s+(.*)", line).groups()
        cp = int(points[0], 16)
        if group not in EMOJI_GROUPS and chr(cp) not in INCLUDED_EMOJI:
            continue
        if float(version) > EMOJI_MAX_VERSION or chr(cp) in EXCLUDED_EMOJI:
            continue
        chosen.append((cp, name))
    return chosen


def write_emoji():
    test_text = fetch(EMOJI_TEST_URL)
    version = re.search(r"^# Version: (\S+)", test_text, re.M).group(1)
    chosen = curate_emoji(test_text)
    if len(chosen) != EMOJI_COUNT:
        sys.exit(f"expected {EMOJI_COUNT} emoji after exclusions, got {len(chosen)}; adjust EXCLUDED_EMOJI")
    rows = "\n".join(f'    "{chr(cp)}",  // {name}' for cp, name in chosen)
    body = f"let emojiWords: [String] = [\n{rows}\n]\n"
    extra = (
        f"//  Rule: curate_emoji(), Unicode emoji {version}, up to E{EMOJI_MAX_VERSION}.\n"
        "//  The Unicode data file is used under the Unicode License v3 (see THIRD_PARTY_LICENSES).\n"
    )
    path = OUT / "WordLists+Emoji.swift"
    path.write_text(swift_header(f"Source: {EMOJI_TEST_URL}.", extra) + body)
    print(f"wrote {path.relative_to(ROOT)} ({len(chosen)} emoji, Unicode emoji {version})")


def main():
    commands = {"eff": write_eff, "emoji": write_emoji}
    if len(sys.argv) != 2 or sys.argv[1] not in commands:
        sys.exit(__doc__)
    commands[sys.argv[1]]()


if __name__ == "__main__":
    main()
